version: '3.8'

services:
  inventory-management-api:
    image: inventory-management-api
    container_name: inventory-management-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
